"""
cpp_export.py
-------------
Generates a C++ function from the current node graph.

The function name comes from the editor's toolbar field.
The Output node's input pins define the return type and variable names.
All other nodes implement to_cpp_expr() to describe their computation.

Algorithm
---------
Starting from each input pin of the Output node, walk backwards through
the data graph recursively (depth-first), building a C++ expression tree.
Inline pin values are used for unconnected inputs.

Result
------
A C++ function string, e.g.:

    // Auto-generated by Node Editor
    float Update_Movement(/* inputs */) {
        float Result = (A + 1.000000f);
        return Result;
    }
"""

from Core.NodeEditorContent.Core.scene import NodeScene

_CPP_TYPE = {
    'float' : 'float',
    'int'   : 'int',
    'bool'  : 'bool',
    'string': 'std::string',
}

_CPP_SUFFIX = {
    'float' : 'f',
    'int'   : '',
    'bool'  : '',
    'string': '',
}

_CPP_LITERAL = {
    'float' : lambda v: f"{float(v):.6f}f",
    'int'   : lambda v: str(int(v)),
    'bool'  : lambda v: "true" if v else "false",
    'string': lambda v: f'"{v}"',
}


def _cpp_type(ptype: str) -> str:
    return _CPP_TYPE.get(ptype, 'auto')


def _literal(ptype: str, value) -> str:
    fn = _CPP_LITERAL.get(ptype)
    if fn:
        try:
            return fn(value)
        except Exception:
            pass
    return str(value)


def _safe_ident(s: str) -> str:
    out = "".join(c if c.isalnum() or c == '_' else '_' for c in str(s))
    return ("_" + out) if (not out or out[0].isdigit()) else out or "_node"


def generate_cpp(scene: NodeScene, func_name: str) -> str:
    """
    Walk the scene graph and produce a C++ function string.

    Parameters
    ----------
    scene     : the live NodeScene
    func_name : user-supplied function name (from toolbar)
    """
    from Core.NodeEditorContent.Core.nodes_builtin import OutputNode

    nodes  = {n.node_id: n for n in scene.nodes}
    wires  = scene.wires

    # data_src[(dst_node_id, dst_in_pin_idx)] = (src_node_id, src_out_pin_idx)
    data_src = {}
    for w in wires:
        try:
            si = w.src.node.out_pins.index(w.src)
            di = w.dst.node.in_pins.index(w.dst)
            data_src[(w.dst.node.node_id, di)] = (w.src.node.node_id, si)
        except ValueError:
            pass

    visited_expr = {}   # (node_id, out_pin_idx) -> cached expression string

    def expr(node_id: str, in_pin_idx: int) -> str:
        """Return C++ expression for the value arriving at an input pin."""
        key = (node_id, in_pin_idx)
        if key not in data_src:
            # unconnected → use inline widget value
            nd  = nodes.get(node_id)
            if nd is None:
                return "0"
            if in_pin_idx < len(nd.in_pins):
                pin = nd.in_pins[in_pin_idx]
                return _literal(pin.pin_type, pin.inline_value())
            return "0"

        src_id, src_pin_idx = data_src[key]
        cache_key = (src_id, src_pin_idx)
        if cache_key in visited_expr:
            return visited_expr[cache_key]

        src_node = nodes.get(src_id)
        if src_node is None:
            return "0"

        ctx = {'expr': expr}
        result = src_node.to_cpp_expr(src_pin_idx, ctx)
        visited_expr[cache_key] = result
        return result

    # find Output node
    out_node = next((n for n in scene.nodes if isinstance(n, OutputNode)), None)
    if out_node is None:
        return "// No Output node in the graph.\nvoid " + _safe_ident(func_name) + "() {}\n"

    safe_name = _safe_ident(func_name or "unnamed_function")
    lines     = []
    lines.append("// Auto-generated by Node Editor")
    lines.append(f"// Function: {func_name}")
    lines.append("")

    # determine return type from first output pin (or void)
    ret_pins = out_node.in_pins
    if not ret_pins:
        lines.append(f"void {safe_name}() {{")
        lines.append("    // No return pins defined on Output node.")
        lines.append("}")
        return "\n".join(lines)

    if len(ret_pins) == 1:
        rtype = _cpp_type(ret_pins[0].pin_type)
        lines.append(f"{rtype} {safe_name}() {{")
    else:
        # multiple returns → void with out-params
        params = ", ".join(
            f"{_cpp_type(p.pin_type)}& {_safe_ident(p.name)}" for p in ret_pins
        )
        lines.append(f"void {safe_name}({params}) {{")

    # body: compute each return value
    for i, pin in enumerate(ret_pins):
        var  = _safe_ident(pin.name)
        ct   = _cpp_type(pin.pin_type)
        val  = expr(out_node.node_id, i)
        lines.append(f"    {ct} {var} = {val};")

    if len(ret_pins) == 1:
        var = _safe_ident(ret_pins[0].name)
        lines.append(f"    return {var};")

    lines.append("}")
    return "\n".join(lines)
