"""
cpp_export.py
-------------
Generates a C++ function from the node graph.

New in this version
-------------------
• Nodes can call self.add_helper(str) to emit lines BEFORE the return.
• Multiple add_helper() calls are supported per node, order preserved.
• inline_script() recursively expands an imported .script inline.
"""

from Core.NodeEditorContent.Core.scene import NodeScene

_CPP_TYPE = {
    'float' : 'float',
    'int'   : 'int',
    'bool'  : 'bool',
    'string': 'std::string',
    'custom': '',
}

_CPP_LITERAL = {
    'float' : lambda v: f"{float(v):.6f}f",
    'int'   : lambda v: str(int(v)),
    'bool'  : lambda v: "true" if v else "false",
    'string': lambda v: f'"{v}"',
    'custom': lambda v: str(v),
}


def _cpp_type(ptype: str) -> str:
    return _CPP_TYPE.get(ptype, 'auto')


def _literal(ptype: str, value) -> str:
    fn = _CPP_LITERAL.get(ptype, _CPP_LITERAL['custom'])
    try:
        return fn(value)
    except Exception:
        return str(value)


def _safe_ident(s: str) -> str:
    out = "".join(c if c.isalnum() or c == '_' else '_' for c in str(s))
    return ("_" + out) if (not out or out[0].isdigit()) else out or "_node"


# ─────────────────────────────────────────────────────────────
#  Main entry point
# ─────────────────────────────────────────────────────────────

def generate_cpp(scene: NodeScene, func_name: str) -> str:
    from Core.NodeEditorContent.Core.nodes_builtin import OutputNode

    helpers   = []
    safe_name = _safe_ident(func_name or "my_function")

    out_node = next((n for n in scene.nodes if isinstance(n, OutputNode)), None)
    if out_node is None:
        return f"// No Output node in the graph.\nvoid {safe_name}() {{}}\n"

    nodes_map = {n.node_id: n for n in scene.nodes}

    data_src = {}
    for w in scene.wires:
        try:
            si = w.src.node.out_pins.index(w.src)
            di = w.dst.node.in_pins.index(w.dst)
            data_src[(w.dst.node.node_id, di)] = (w.src.node.node_id, si)
        except ValueError:
            pass

    visited = {}

    def expr(node_id: str, in_pin_idx: int) -> str:
        key = (node_id, in_pin_idx)
        if key not in data_src:
            nd = nodes_map.get(node_id)
            if nd is None:
                return "0"
            if in_pin_idx < len(nd.in_pins):
                pin = nd.in_pins[in_pin_idx]
                return _literal(pin.pin_type, pin.inline_value())
            return "0"

        src_id, src_pin = data_src[key]
        cache_key = (src_id, src_pin)
        if cache_key in visited:
            return visited[cache_key]

        src_node = nodes_map.get(src_id)
        if src_node is None:
            return "0"

        src_node._helpers = []
        ctx = {
            'expr'        : expr,
            'helpers_list': helpers,
            'params'      : {},
        }
        result = src_node.to_cpp_expr(src_pin, ctx)

        for h in getattr(src_node, '_helpers', []):
            helpers.append(h)

        visited[cache_key] = result
        return result

    ret_pins  = out_node.in_pins
    if not ret_pins:
        return f"void {safe_name}() {{\n    // No return pins.\n}}\n"

    ret_exprs = [(pin, expr(out_node.node_id, i)) for i, pin in enumerate(ret_pins)]

    # ── assemble ──────────────────────────────────────────────
    lines = [
        "// Auto-generated by Node Editor",
        f"// Function: {func_name}",
        "",
    ]

    if len(ret_pins) == 1:
        rtype = _cpp_type(ret_pins[0].pin_type) or ret_pins[0].pin_type
        lines.append(f"{rtype} {safe_name}() {{")
    else:
        params_str = ", ".join(
            f"{_cpp_type(p.pin_type) or p.pin_type}& {_safe_ident(p.name)}"
            for p in ret_pins
        )
        lines.append(f"void {safe_name}({params_str}) {{")

    # helpers block
    if helpers:
        for h in helpers:
            for line in h.strip().splitlines():
                lines.append(f"    {line}")
        lines.append("")

    # variable assignments
    for pin, val in ret_exprs:
        var = _safe_ident(pin.name)
        ct  = _cpp_type(pin.pin_type) or pin.pin_type
        lines.append(f"    {ct} {var} = {val};")

    if len(ret_pins) == 1:
        lines.append(f"    return {_safe_ident(ret_pins[0].name)};")

    lines.append("}")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────
#  Script inlining
# ─────────────────────────────────────────────────────────────

def inline_script(script_data: dict, out_pin_index: int,
                  params: dict, helpers_list: list) -> str:
    """
    Recursively inline a .script's output expression.
    params        : {input_name: cpp_expr_string}
    helpers_list  : parent's running helpers list (appended in-place)
    """
    nodes_list = script_data.get('nodes', [])
    wires_list = script_data.get('wires', [])
    nodes_map  = {nd['id']: nd for nd in nodes_list}

    data_src = {}
    for w in wires_list:
        data_src[(w['dst'], w['dp'])] = (w['src'], w['sp'])

    visited = {}

    def expr(node_id: str, in_pin_idx: int) -> str:
        key = (node_id, in_pin_idx)
        if key not in data_src:
            nd   = nodes_map.get(node_id, {})
            ck   = nd.get('class_key', '')
            pins = nd.get('in_pins', [])
            if ck == 'InputNode':
                name = nd.get('s_name', 'input')
                return params.get(name,
                       _literal(nd.get('s_type', 'float'), nd.get('s_default', 0)))
            if in_pin_idx < len(pins):
                p = pins[in_pin_idx]
                return _literal(p.get('type', 'float'), p.get('value', 0))
            return "0"

        src_id, src_pin = data_src[key]
        cache_key = (src_id, src_pin)
        if cache_key in visited:
            return visited[cache_key]

        src_nd = nodes_map.get(src_id, {})
        result = _dict_node_expr(src_nd, src_nd.get('class_key', ''),
                                 src_pin, expr, helpers_list,
                                 params, script_data)
        visited[cache_key] = result
        return result

    out_nd = next((nd for nd in nodes_list if nd.get('class_key') == 'OutputNode'), None)
    if out_nd is None:
        return "0"

    in_pins = out_nd.get('in_pins', [])
    if out_pin_index >= len(in_pins):
        return "0"

    return expr(out_nd['id'], out_pin_index)


def _dict_node_expr(nd: dict, ck: str, out_pin: int,
                    expr_fn, helpers_list: list,
                    params: dict, script_data: dict) -> str:

    if ck == 'InputNode':
        name = nd.get('s_name', 'input')
        return params.get(name,
               _literal(nd.get('s_type', 'float'), nd.get('s_default', 0)))

    if ck == 'MathNode':
        op = nd.get('op', nd.get('meta', {}).get('title', '+'))
        a  = expr_fn(nd['id'], 0)
        b  = expr_fn(nd['id'], 1)
        return f"({a} {op} {b})"

    if ck == 'ScriptNode':
        import os
        import json as _json
        path = nd.get('script_path', '')
        if os.path.isfile(path):
            with open(path, 'r', encoding='utf-8') as f:
                sub_data = _json.load(f)
            from Core.NodeEditorContent.Core.nodes_script import _extract_inputs
            sub_inputs = _extract_inputs(sub_data)
            sub_params = {inp['name']: expr_fn(nd['id'], i)
                          for i, inp in enumerate(sub_inputs)}
            return inline_script(sub_data, out_pin, sub_params, helpers_list)
        return "0"

    from Core.NodeEditorContent.Core.node_loader import REGISTRY
    if ck in REGISTRY:
        import uuid
        tmp      = REGISTRY[ck](str(uuid.uuid4())[:8])
        tmp._helpers = []
        ctx = {'expr': expr_fn, 'helpers_list': helpers_list, 'params': params}
        result = tmp.to_cpp_expr(out_pin, ctx)
        for h in tmp._helpers:
            helpers_list.append(h)
        return result

    out_pins = nd.get('out_pins', [])
    if out_pin < len(out_pins):
        return _safe_ident(out_pins[out_pin].get('name', 'value'))
    return "0"